services:

  ingest-api:
    build: ./ingest-api
    ports: 
      - 8000:8000
    volumes:
      - ./ingest-api:/app
      - ingest-api-venv:/app/.venv

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      # Set Kafka in KRaft mode
      KAFKA_CLUSTER_ID: "YWFhYjc2YWUtNmYwZi00Nm" # A base64 UUID of exactly 22 characters
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    volumes:
      - ./data/kafka/logs:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  kafka-init:
    image: apache/kafka:latest
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    command: ["/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--create", "--topic", "telemetry.raw", "--partitions", "3", "--config", "retention.bytes=-1", "--replication-factor", "1"]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports: 
      - 8080:8080
    environment:
      - DYNAMIC_CONFIG_ENABLED='true'
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    volumes:
      - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml

volumes:
  ingest-api-venv:
